lsi: false
safe: true
source: smaameri/semantic-labs
incremental: false
highlighter: rouge
theme: jekyll-theme-minimal
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
